# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/build-N210R4/u2plus.xdc

# IP: ip/fifo_xlnx_16x19_2clk/fifo_xlnx_16x19_2clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_16x19_2clk || ORIG_REF_NAME==fifo_xlnx_16x19_2clk} -quiet] -quiet

# IP: ip/fifo_xlnx_512x36_2clk/fifo_xlnx_512x36_2clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk || ORIG_REF_NAME==fifo_xlnx_512x36_2clk} -quiet] -quiet

# IP: ip/fifo_xlnx_64x36_2clk/fifo_xlnx_64x36_2clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_64x36_2clk || ORIG_REF_NAME==fifo_xlnx_64x36_2clk} -quiet] -quiet

# IP: ip/fifo_xlnx_2Kx36_2clk/fifo_xlnx_2Kx36_2clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_2Kx36_2clk || ORIG_REF_NAME==fifo_xlnx_2Kx36_2clk} -quiet] -quiet

# IP: ip/fifo_xlnx_512x36_2clk_prog_full/fifo_xlnx_512x36_2clk_prog_full.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_prog_full || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_prog_full} -quiet] -quiet

# IP: ip/fifo_xlnx_32x36_2clk/fifo_xlnx_32x36_2clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_32x36_2clk || ORIG_REF_NAME==fifo_xlnx_32x36_2clk} -quiet] -quiet

# IP: ip/fifo_xlnx_512x36_2clk_18to36/fifo_xlnx_512x36_2clk_18to36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_18to36 || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_18to36} -quiet] -quiet

# IP: ip/fifo_xlnx_512x36_2clk_36to18/fifo_xlnx_512x36_2clk_36to18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_36to18 || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_36to18} -quiet] -quiet

# IP: ip/fifo_xlnx_16x40_2clk/fifo_xlnx_16x40_2clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_xlnx_16x40_2clk || ORIG_REF_NAME==fifo_xlnx_16x40_2clk} -quiet] -quiet

# IP: ip/RAM/RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_16x19_2clk/fifo_xlnx_16x19_2clk.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_16x19_2clk || ORIG_REF_NAME==fifo_xlnx_16x19_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_16x19_2clk/fifo_xlnx_16x19_2clk_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_16x19_2clk || ORIG_REF_NAME==fifo_xlnx_16x19_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk/fifo_xlnx_512x36_2clk.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk || ORIG_REF_NAME==fifo_xlnx_512x36_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk/fifo_xlnx_512x36_2clk_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk || ORIG_REF_NAME==fifo_xlnx_512x36_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_64x36_2clk/fifo_xlnx_64x36_2clk.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_64x36_2clk || ORIG_REF_NAME==fifo_xlnx_64x36_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_64x36_2clk/fifo_xlnx_64x36_2clk_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_64x36_2clk || ORIG_REF_NAME==fifo_xlnx_64x36_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_2Kx36_2clk/fifo_xlnx_2Kx36_2clk.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_2Kx36_2clk || ORIG_REF_NAME==fifo_xlnx_2Kx36_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_2Kx36_2clk/fifo_xlnx_2Kx36_2clk_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_2Kx36_2clk || ORIG_REF_NAME==fifo_xlnx_2Kx36_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_prog_full/fifo_xlnx_512x36_2clk_prog_full.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_prog_full || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_prog_full} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_prog_full/fifo_xlnx_512x36_2clk_prog_full_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_prog_full || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_prog_full} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_32x36_2clk/fifo_xlnx_32x36_2clk.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_32x36_2clk || ORIG_REF_NAME==fifo_xlnx_32x36_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_32x36_2clk/fifo_xlnx_32x36_2clk_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_32x36_2clk || ORIG_REF_NAME==fifo_xlnx_32x36_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_18to36/fifo_xlnx_512x36_2clk_18to36.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_18to36 || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_18to36} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_18to36/fifo_xlnx_512x36_2clk_18to36_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_18to36 || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_18to36} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_36to18/fifo_xlnx_512x36_2clk_36to18.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_36to18 || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_36to18} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_36to18/fifo_xlnx_512x36_2clk_36to18_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_512x36_2clk_36to18 || ORIG_REF_NAME==fifo_xlnx_512x36_2clk_36to18} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_16x40_2clk/fifo_xlnx_16x40_2clk.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_16x40_2clk || ORIG_REF_NAME==fifo_xlnx_16x40_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_16x40_2clk/fifo_xlnx_16x40_2clk_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_xlnx_16x40_2clk || ORIG_REF_NAME==fifo_xlnx_16x40_2clk} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/RAM/RAM_ooc.xdc
