# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.runs/synth_1/u2plus.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k160tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.cache/wt [current_project]
set_property parent.project_path D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/bootloader.coe
read_verilog {
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/i2c/rtl/verilog/timescale.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/i2c/rtl/verilog/i2c_master_defines.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/spi/rtl/verilog/spi_defines.v
}
set_property file_type "Verilog Header" [get_files D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/i2c/rtl/verilog/timescale.v]
set_property file_type "Verilog Header" [get_files D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/i2c/rtl/verilog/i2c_master_defines.v]
set_property file_type "Verilog Header" [get_files D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/spi/rtl/verilog/spi_defines.v]
read_verilog -library xil_defaultlib {
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/CRC16_D16.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/acc.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/add2.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/add2_and_clip.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/add2_and_clip_reg.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/add2_and_round.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/add2_and_round_reg.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/add2_reg.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/udp/add_onescomp.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/add_routing_header.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/address_filter.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/address_filter_promisc.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/bin2gray.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/bootram.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/buffer_int2.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/top/N2x0/capture_ddrlvds.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/cic_dec_shifter.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/cic_decim.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/cic_int_shifter.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/cic_interp.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/cic_strober.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/clip.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/clip_reg.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/cordic_stage.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/cordic_z24.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/crc.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/crossbar36.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/dbsm.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/ddc_chain.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/8b10b/decode_8b10b.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/delay_line.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/double_buffer.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/dsp_rx_glue.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/dsp_tx_glue.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/dspengine_16to8.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/dspengine_8to16.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/duc_chain.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/8b10b/encode_8b10b.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/miim/eth_clockgen.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/miim/eth_miim.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/miim/eth_outputcontrol.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/miim/eth_shiftreg.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/ethtx_realign.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/extramfifo/ext_fifo.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/udp/fifo19_rxrealign.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/fifo19_to_fifo36.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/fifo36_mux.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/fifo36_to_ll8.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/fifo_2clock.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/fifo_2clock_cascade.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/fifo_cascade.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/fifo_long.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/fifo_short.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/flow_ctrl_rx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/flow_ctrl_tx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/gen_context_pkt.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/gpio_atr.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/hb_dec.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/hb_interp.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/i2c/rtl/verilog/i2c_master_bit_ctrl.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/i2c/rtl/verilog/i2c_master_byte_ctrl.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/i2c/rtl/verilog/i2c_master_top.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/ll8_shortfifo.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/ll8_to_fifo19.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/ll8_to_txmac.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/medfifo.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/extramfifo/nobl_fifo.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/extramfifo/nobl_if.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/oneshot_2clk.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/packet_dispatcher36_x4.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/packet_router.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/pic.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/pipectrl.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/pipestage.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/priority_enc.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/udp/prot_eng_tx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/quad_uart.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/ram_2port.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/ram_harvard2.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/extramfifo/refill_randomizer.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/reset_sync.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/round.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/round_reg.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/round_sd.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/rx_dcoffset.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/rx_frontend.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/rxmac_to_ll8.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/serdes/serdes.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/serdes/serdes_fc_rx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/serdes/serdes_fc_tx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/serdes/serdes_rx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/serdes/serdes_tx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/setting_reg.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/settings_bus.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/settings_bus_crossclock.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/settings_fifo_ctrl.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/shortfifo.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/sign_extend.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/simple_gemac.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/simple_gemac_rx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/simple_gemac_tx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/simple_gemac_wb.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/simple_gemac/simple_gemac_wrapper.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/simple_spi_core.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/simple_uart_rx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/simple_uart_tx.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/small_hb_dec.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/small_hb_int.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/spi/rtl/verilog/spi_clgen.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/spi/rtl/verilog/spi_shift.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/spi/rtl/verilog/spi_top.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/splitter36.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/srl.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/system_control.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/timing/time_64bit.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/timing/time_compare.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/timing/time_receiver.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/timing/time_sender.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/top/N2x0/transmit_ddrlvds.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/trigger_context_pkt.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/sdr_lib/tx_frontend.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/top/N2x0/u2plus_core.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/user_settings.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/fifo/valve36.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/vita_rx_chain.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/vita_rx_control.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/vita_rx_engine_glue.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/vita_rx_framer.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/vita_tx_chain.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/vita_tx_control.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/vita_tx_deframer.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/vrt/vita_tx_engine_glue.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/wb_1master.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/control_lib/wb_readback_mux.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/wbicapetwo/trunk/rtl/wbicapetwo.v
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/top/N2x0/u2plus.v
}
read_vhdl -library xil_defaultlib {
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/zpu/wishbone/wishbone_pkg.vhd
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/zpu/core/zpu_config.vhd
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/zpu/core/zpupkg.vhd
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/zpu/core/zpu_core.vhd
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/zpu/zpu_top_pkg.vhd
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/zpu/wishbone/zpu_system.vhd
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/zpu/wishbone/zpu_wb_bridge.vhd
  D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/imports/usrp2/opencores/zpu/zpu_wb_top.vhd
}
read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_16x19_2clk/fifo_xlnx_16x19_2clk.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_16x19_2clk/fifo_xlnx_16x19_2clk.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_16x19_2clk/fifo_xlnx_16x19_2clk_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_512x36_2clk/fifo_xlnx_512x36_2clk.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk/fifo_xlnx_512x36_2clk.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk/fifo_xlnx_512x36_2clk_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_64x36_2clk/fifo_xlnx_64x36_2clk.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_64x36_2clk/fifo_xlnx_64x36_2clk.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_64x36_2clk/fifo_xlnx_64x36_2clk_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_2Kx36_2clk/fifo_xlnx_2Kx36_2clk.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_2Kx36_2clk/fifo_xlnx_2Kx36_2clk.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_2Kx36_2clk/fifo_xlnx_2Kx36_2clk_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_512x36_2clk_prog_full/fifo_xlnx_512x36_2clk_prog_full.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_prog_full/fifo_xlnx_512x36_2clk_prog_full.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_prog_full/fifo_xlnx_512x36_2clk_prog_full_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_32x36_2clk/fifo_xlnx_32x36_2clk.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_32x36_2clk/fifo_xlnx_32x36_2clk.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_32x36_2clk/fifo_xlnx_32x36_2clk_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_512x36_2clk_18to36/fifo_xlnx_512x36_2clk_18to36.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_18to36/fifo_xlnx_512x36_2clk_18to36.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_18to36/fifo_xlnx_512x36_2clk_18to36_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_512x36_2clk_36to18/fifo_xlnx_512x36_2clk_36to18.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_36to18/fifo_xlnx_512x36_2clk_36to18.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_512x36_2clk_36to18/fifo_xlnx_512x36_2clk_36to18_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/fifo_xlnx_16x40_2clk/fifo_xlnx_16x40_2clk.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_16x40_2clk/fifo_xlnx_16x40_2clk.xdc]
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/fifo_xlnx_16x40_2clk/fifo_xlnx_16x40_2clk_clocks.xdc]

read_ip -quiet D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all d:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.gen/sources_1/ip/RAM/RAM_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/constrs_1/imports/build-N210R4/u2plus.xdc
set_property used_in_implementation false [get_files D:/GitHub/Kintex_FPGA/Kintex_FPGA_vivado.srcs/constrs_1/imports/build-N210R4/u2plus.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top u2plus -part xc7k160tfbg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef u2plus.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file u2plus_utilization_synth.rpt -pb u2plus_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
